### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheCoder11** [ItsWagPvP/EconomyPlus#15]
**Describe the bug**
me.itswagpvp.economyplus.misc.Logger.plugin is reported as null, causing a cascade of "too many open files" errors

**Expected behavior**
I expected the plugin to correctly log to the terminal

**Screenshots**
java.lang.NullPointerException: Cannot invoke "me.itswagpvp.economyplus.EconomyPlus.getLogger()" because "me.itswagpvp.economyplus.misc.Logger.plugin" is null
	at me.itswagpvp.economyplus.misc.Logger.getLogger(Logger.java:13) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.dbStorage.sqlite.Database.lambda$setTokens$1(Database.java:108) ~[EconomyPlus.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-388]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-388]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[2021-12-03-1.log](https://github.com/ItsWagPvP/EconomyPlus/files/7658298/2021-12-03-1.log)
.

**Comment by ItsWagPvP** [comment]
Will be fixed in V3.1
