### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thekepaag** [ItsWagPvP/EconomyPlus#22]
**Describe the bug**
WARN spam in console

**Expected behavior**
[12:48:45] [Craft Scheduler Thread - 6 - PlaceholderAPI/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.11.1 generated an exception while executing task 709
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at me.itswagpvp.economyplus.vault.VEconomy.getBalance(VEconomy.java:82) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.vault.VEconomy.getBalance(VEconomy.java:88) ~[EconomyPlus.jar:?]
	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:223) ~[?:?]
	at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-176]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ItsWagPvP** [comment]
"/ep debug" output?

**Comment by thekepaag** [comment]
![image](https://user-images.githubusercontent.com/39769703/153276374-cee97adc-a9af-435b-9339-3f2106ee707b.png)

**Comment by ItsWagPvP** [comment]
i've fixed this in 3.7 (releasing it tonight or tomorrow)
