### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UUID string: cond_b

### ISSUE THREAD

**Issue by condblock** [ItsWagPvP/EconomyPlus#26]
java.lang.IllegalArgumentException: Invalid UUID string: cond_b
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at me.itswagpvp.economyplus.misc.BalTopManager.loadFromDatabase(BalTopManager.java:27) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.misc.BalTopManager.<init>(BalTopManager.java:18) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.hooks.holograms.HolographicDisplays.refreshHologram(HolographicDisplays.java:82) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.EconomyPlus.lambda$loadHolograms$1(EconomyPlus.java:310) ~[EconomyPlus.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1560]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

cond_b is my nickname.... can i fix it?

**Comment by ItsWagPvP** [comment]
have you changed storage type without converting the db?

**Comment by condblock** [comment]
> have you changed storage type without converting the db?

nope i never changed it

**Comment by condblock** [comment]
other players are ok but my uuid errors

**Comment by Lmaxplay** [comment]
Try clearing the playerdata @condblock

**Comment by ItsWagPvP** [comment]
just remove your name from the db, it seems that the db is setted to work with uuid and you are saved as nickname
