### ISSUE TITLE
EconomyPlus 4.5 newest update 

### ISSUE THREAD

**Issue by Chucky891** [ItsWagPvP/EconomyPlus#44]
[14:34:39 ERROR]: Error occurred while enabling EconomyPlus v4.5 (Is it up to date?)
java.lang.NumberFormatException: multiple points
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
        at me.itswagpvp.economyplus.EconomyPlus.onEnable(EconomyPlus.java:119) ~[EconomyPlus.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-232]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-232]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-232]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:34:39 INFO]: [EconomyPlus] Disabling EconomyPlus v4.5
[14:34:39 INFO]: +------------------------------------+
[14:34:39 INFO]:              EconomyPlus
[14:34:39 INFO]:               Disabling
[14:34:39 INFO]: 
[14:34:39 INFO]: -> Stopping threads...
[14:34:39 INFO]: -> Closing database connection
[14:34:39 INFO]: +------------------------------------+

**Comment by jakepronger** [comment]
Sorry for the hassle but do you think you could send the full log of the server just so I can find out what triggers this issue? Or maybe what command you executed? (I'm not able to replicate the issue at this current time)

**Comment by jakepronger** [comment]
Can you please elaborate if you can? How did you replicate this issue? Can you send full logs or triggers to what caused this issue?
