### ISSUE TITLE
[BUG] SQL error on bootup

### ISSUE THREAD

**Issue by ItzYanick** [ItsWagPvP/EconomyPlus#5]
**Describe the bug**
When I bootup the server it shows the following SQL error message

```
[21:17:00] [Server thread/INFO]: [EconomyPlus] Enabling EconomyPlus v2.3
[21:17:00] [Server thread/INFO]: +------------------------------------+
[21:17:00] [Server thread/INFO]:              EconomyPlus
[21:17:00] [Server thread/INFO]:               Enabling
[21:17:00] [Server thread/INFO]: 
[21:17:00] [Server thread/INFO]: -> Loading core!
[21:17:00] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: bank)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1012)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1024)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.DB.throwex(DB.java:989)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.DB.prepare(DB.java:257)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[21:17:00] [Server thread/WARN]: 	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[21:17:00] [Server thread/WARN]: 	at me.itswagpvp.economyplus.storage.sqlite.Database.updateTable(Database.java:51)
[21:17:00] [Server thread/WARN]: 	at me.itswagpvp.economyplus.storage.sqlite.Database.initialize(Database.java:37)
[21:17:00] [Server thread/WARN]: 	at me.itswagpvp.economyplus.storage.sqlite.SQLite.load(SQLite.java:64)
[21:17:00] [Server thread/WARN]: 	at me.itswagpvp.economyplus.EconomyPlus.loadDatabase(EconomyPlus.java:185)
[21:17:00] [Server thread/WARN]: 	at me.itswagpvp.economyplus.EconomyPlus.onEnable(EconomyPlus.java:91)
[21:17:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:17:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[21:17:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:17:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:505)
[21:17:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:419)
[21:17:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:604)
[21:17:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[21:17:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995)
[21:17:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[21:17:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:17:00] [Server thread/INFO]:    - Database: Loaded (SQLite)
[21:17:00] [Server thread/INFO]:    - Vault: Hooked
[21:17:00] [Server thread/INFO]:    - Events: Loaded
[21:17:00] [Server thread/INFO]:    - Commands: Loaded
[21:17:00] [Server thread/INFO]: 
[21:17:00] [Server thread/INFO]: -> Loading hooks!
[21:17:00] [Server thread/INFO]:    - bStats: Loaded
[21:17:00] [Server thread/INFO]:    - HolographicDisplays: Found
[21:17:00] [Server thread/INFO]: 
[21:17:00] [Server thread/INFO]: -> Loading placeholders:
[21:17:00] [Server thread/INFO]:    - MVdWPlaceholderAPI: Not found!
[21:17:00] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: economyplus
[21:17:00] [Server thread/INFO]:    - PlaceholderAPI: Done!
[21:17:00] [Server thread/INFO]: 
[21:17:00] [Server thread/INFO]: +---------------[ 20ms ]-------------+
```

**To Reproduce**
1. Install the plugin
2. Leave config like it is (H2 as database)
3. Start Server
4. Stop Server
5. Start Server again

**Comment by ItsWagPvP** [comment]
this problem will be fixed in the next version
