### ISSUE TITLE
[BUG] baltop

### ISSUE THREAD

**Issue by rkfsociety** [ItsWagPvP/EconomyPlus#59]
[22:52:41] [Server thread/INFO]: rkfsociety issued server command: /baltop
[22:52:41] [Craft Scheduler Thread - 58 - EconomyPlus/WARN]: [EconomyPlus] Plugin EconomyPlus v4.9 generated an exception while executing task 78878
java.lang.IllegalArgumentException: Invalid UUID string: rkfsociety
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at me.itswagpvp.economyplus.misc.BalTopManager.loadFromDatabase(BalTopManager.java:29) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.misc.BalTopManager.<init>(BalTopManager.java:20) ~[EconomyPlus.jar:?]
	at me.itswagpvp.economyplus.commands.BalTop.lambda$onCommand$0(BalTop.java:30) ~[EconomyPlus.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-379]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by jakepronger** [comment]
I'll take a look at this issue later and try to fix it.

**Comment by jakepronger** [comment]
You might have a corrupted database; in future the plugin may have an option to try fix unconverted options. If your able to provide more information that would be great. You could try modifying your database. There will also be an update soon regarding balance top and fixing performance issues. If you still need help reopen this ticket.
